/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRouterClient } from './IRouterClient.js';
export type { MockCCIPRouter } from './MockCCIPRouter.js';