// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IClaimManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IClaimManager";
  readonly sourceName: "test/interfaces/IClaimManager.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"claimId","type":"uint256"}],"name":"claims","outputs":[{"components":[{"internalType":"bytes32","name":"policyId","type":"bytes32"},{"internalType":"address","name":"claimant","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint64","name":"startTs","type":"uint64"},{"internalType":"uint64","name":"endTs","type":"uint64"},{"internalType":"uint64","name":"dstChainSelector","type":"uint64"},{"internalType":"bytes","name":"dstPayoutVault","type":"bytes"},{"internalType":"bool","name":"finalized","type":"bool"},{"internalType":"bool","name":"approved","type":"bool"},{"internalType":"uint256","name":"yes","type":"uint256"},{"internalType":"uint256","name":"no","type":"uint256"}],"internalType":"struct IClaimManager.Claim","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"claimId","type":"uint256"}],"name":"finalizeClaim","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"policyId","type":"bytes32"},{"internalType":"address","name":"claimantOnArbitrum","type":"address"},{"internalType":"uint256","name":"amountPYUSD","type":"uint256"},{"internalType":"uint64","name":"dstChainSelector","type":"uint64"},{"internalType":"bytes","name":"dstPayoutVault","type":"bytes"}],"name":"openClaim","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"claimId","type":"uint256"}],"name":"voteNo","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"claimId","type":"uint256"}],"name":"voteYes","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/test/interfaces/IClaimManager.sol";
  readonly buildInfoId: "solc-0_8_24-7206415546ac20b85133b31bb5c4efa2e6b80e38";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IClaimManager"]: IClaimManager$Type;
    ["test/interfaces/IClaimManager.sol:IClaimManager"]: IClaimManager$Type;
  }
}