/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface ILPVaultInterface extends Interface {
    getFunction(nameOrSignature: "deposit" | "finalizeWithdraw" | "requestWithdraw" | "stakes" | "totalShares"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeWithdraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestWithdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakes', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalShares', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalShares', data: BytesLike): Result;
  }

  

  export interface ILPVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): ILPVault;
    waitForDeployment(): Promise<this>;

    interface: ILPVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deposit: TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    finalizeWithdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requestWithdraw: TypedContractMethod<
      [shares: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakes: TypedContractMethod<
      [lp: AddressLike, ],
      [[bigint, bigint] & {shares: bigint, lockedUntil: bigint }],
      'view'
    >
    

    
    totalShares: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeWithdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestWithdraw'): TypedContractMethod<
      [shares: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakes'): TypedContractMethod<
      [lp: AddressLike, ],
      [[bigint, bigint] & {shares: bigint, lockedUntil: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'totalShares'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }