/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IClaimManager } from './IClaimManager.js';
export type { ILPVault } from './ILPVault.js';
export type { IPayoutVault } from './IPayoutVault.js';
export type { IPolicyManager } from './IPolicyManager.js';
export type { IPremiumVault } from './IPremiumVault.js';
export type { IVotingMirror } from './IVotingMirror.js';