/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace IPolicyManager {
      
    export type PolicyStruct = {poolId: BytesLike, buyer: AddressLike, coverageAmount: BigNumberish, startTs: BigNumberish, endTs: BigNumberish, policyRef: BytesLike, tokenId: BigNumberish, active: boolean}

    export type PolicyStructOutput = [poolId: string, buyer: string, coverageAmount: bigint, startTs: bigint, endTs: bigint, policyRef: string, tokenId: bigint, active: boolean] & {poolId: string, buyer: string, coverageAmount: bigint, startTs: bigint, endTs: bigint, policyRef: string, tokenId: bigint, active: boolean }
  
    }

  export interface IPolicyManagerInterface extends Interface {
    getFunction(nameOrSignature: "_ccipReceive" | "allowlistSender" | "allowlistSourceChain" | "ccipReceive" | "getPolicy"): FunctionFragment;

    

    encodeFunctionData(functionFragment: '_ccipReceive', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'allowlistSender', values: [BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'allowlistSourceChain', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'ccipReceive', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getPolicy', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: '_ccipReceive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowlistSender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowlistSourceChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ccipReceive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPolicy', data: BytesLike): Result;
  }

  

  export interface IPolicyManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPolicyManager;
    waitForDeployment(): Promise<this>;

    interface: IPolicyManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    _ccipReceive: TypedContractMethod<
      [message: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    allowlistSender: TypedContractMethod<
      [sender: BytesLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    allowlistSourceChain: TypedContractMethod<
      [selector: BigNumberish, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    ccipReceive: TypedContractMethod<
      [message: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getPolicy: TypedContractMethod<
      [policyId: BytesLike, ],
      [IPolicyManager.PolicyStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: '_ccipReceive'): TypedContractMethod<
      [message: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowlistSender'): TypedContractMethod<
      [sender: BytesLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowlistSourceChain'): TypedContractMethod<
      [selector: BigNumberish, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ccipReceive'): TypedContractMethod<
      [message: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPolicy'): TypedContractMethod<
      [policyId: BytesLike, ],
      [IPolicyManager.PolicyStructOutput],
      'view'
    >;

    

    filters: {
      
    };
  }