/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IPolicyManagerViewInterface extends Interface {
    getFunction(nameOrSignature: "policies"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'policies', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'policies', data: BytesLike): Result;
  }

  

  export interface IPolicyManagerView extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPolicyManagerView;
    waitForDeployment(): Promise<this>;

    interface: IPolicyManagerViewInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    policies: TypedContractMethod<
      [policyId: BytesLike, ],
      [[string, string, bigint, bigint, bigint, string, bigint, boolean] & {poolId: string, buyer: string, coverageAmount: bigint, startTs: bigint, endTs: bigint, policyRef: string, tokenId: bigint, active: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'policies'): TypedContractMethod<
      [policyId: BytesLike, ],
      [[string, string, bigint, bigint, bigint, string, bigint, boolean] & {poolId: string, buyer: string, coverageAmount: bigint, startTs: bigint, endTs: bigint, policyRef: string, tokenId: bigint, active: boolean }],
      'view'
    >;

    

    filters: {
      
    };
  }