// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IPolicyManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IPolicyManager";
  readonly sourceName: "test/interfaces/IPolicyManager.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"message","type":"bytes"}],"name":"_ccipReceive","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes","name":"sender","type":"bytes"},{"internalType":"bool","name":"allowed","type":"bool"}],"name":"allowlistSender","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint64","name":"selector","type":"uint64"},{"internalType":"bool","name":"allowed","type":"bool"}],"name":"allowlistSourceChain","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes","name":"message","type":"bytes"}],"name":"ccipReceive","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"bytes32","name":"policyId","type":"bytes32"}],"name":"getPolicy","outputs":[{"components":[{"internalType":"bytes32","name":"poolId","type":"bytes32"},{"internalType":"address","name":"buyer","type":"address"},{"internalType":"uint256","name":"coverageAmount","type":"uint256"},{"internalType":"uint64","name":"startTs","type":"uint64"},{"internalType":"uint64","name":"endTs","type":"uint64"},{"internalType":"bytes32","name":"policyRef","type":"bytes32"},{"internalType":"uint256","name":"tokenId","type":"uint256"},{"internalType":"bool","name":"active","type":"bool"}],"internalType":"struct IPolicyManager.Policy","name":"","type":"tuple"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/test/interfaces/IPolicyManager.sol";
  readonly buildInfoId: "solc-0_8_24-7206415546ac20b85133b31bb5c4efa2e6b80e38";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IPolicyManager"]: IPolicyManager$Type;
    ["test/interfaces/IPolicyManager.sol:IPolicyManager"]: IPolicyManager$Type;
  }
}