/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPremiumVault, IPremiumVaultInterface } from "../../../test/interfaces/IPremiumVault.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "dstChainSelector",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "hederaReceiver",
        "type": "bytes"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "poolId",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "coverageAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint64",
            "name": "startTs",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "endTs",
            "type": "uint64"
          },
          {
            "internalType": "bytes32",
            "name": "policyRef",
            "type": "bytes32"
          }
        ],
        "internalType": "struct IPremiumVault.PolicyTerms",
        "name": "terms",
        "type": "tuple"
      },
      {
        "internalType": "uint256",
        "name": "premiumPYUSD",
        "type": "uint256"
      }
    ],
    "name": "buyCoverage",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "premiumPYUSD",
        "type": "uint256"
      }
    ],
    "name": "previewAllocation",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "toLP",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "toReserve",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "dstChainSelector",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "hederaReceiver",
        "type": "bytes"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "poolId",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "coverageAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint64",
            "name": "startTs",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "endTs",
            "type": "uint64"
          },
          {
            "internalType": "bytes32",
            "name": "policyRef",
            "type": "bytes32"
          }
        ],
        "internalType": "struct IPremiumVault.PolicyTerms",
        "name": "terms",
        "type": "tuple"
      }
    ],
    "name": "quoteCCIPFee",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IPremiumVault__factory {
    static readonly abi = _abi;
    static createInterface(): IPremiumVaultInterface {
      return new Interface(_abi) as IPremiumVaultInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPremiumVault {
      return new Contract(address, _abi, runner) as unknown as IPremiumVault;
    }
  }
  