/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockCcipRouterSol from './MockCCIPRouter.sol/index.js';
export type { mockCcipRouterSol };
export type { MockPYUSD } from './MockPYUSD.js';