/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IVotingMirrorInterface extends Interface {
    getFunction(nameOrSignature: "totalPower" | "vPowerOf"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'totalPower', values?: undefined): string;
encodeFunctionData(functionFragment: 'vPowerOf', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'totalPower', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vPowerOf', data: BytesLike): Result;
  }

  

  export interface IVotingMirror extends BaseContract {
    
    connect(runner?: ContractRunner | null): IVotingMirror;
    waitForDeployment(): Promise<this>;

    interface: IVotingMirrorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    totalPower: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vPowerOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'totalPower'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vPowerOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }