/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as claimManagerSol from './ClaimManager.sol/index.js';
export type { claimManagerSol };
import type * as lpVaultSol from './LPVault.sol/index.js';
export type { lpVaultSol };
import type * as payoutVaultSol from './PayoutVault.sol/index.js';
export type { payoutVaultSol };
import type * as policyManagerSol from './PolicyManager.sol/index.js';
export type { policyManagerSol };
import type * as votingMirrorSol from './VotingMirror.sol/index.js';
export type { votingMirrorSol };
import type * as mocks from './mocks/index.js';
export type { mocks };
export type { PremiumVault } from './PremiumVault.js';