/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { CCIPReceiver, CCIPReceiverInterface } from "../../VotingMirror.sol/CCIPReceiver.js";

  const _abi = [
  {
    "inputs": [],
    "name": "router",
    "outputs": [
      {
        "internalType": "contract IRouterClient",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class CCIPReceiver__factory {
    static readonly abi = _abi;
    static createInterface(): CCIPReceiverInterface {
      return new Interface(_abi) as CCIPReceiverInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): CCIPReceiver {
      return new Contract(address, _abi, runner) as unknown as CCIPReceiver;
    }
  }
  